image:
  pullPolicy: IfNotPresent
  # Shared by website and blog images.
  tag: "28f8ebf"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: "bonnal-cloud"

apps:
  website:
    enabled: true
    replicaCount: 1
    image:
      repository: ghcr.io/nathaelb/bonnal-cloud-website
    ingress:
      host: bonnal.cloud
  blog:
    enabled: true
    replicaCount: 1
    image:
      repository: ghcr.io/nathaelb/bonnal-cloud-blog
    ingress:
      host: blog.bonnal.cloud

serviceAccount:
  create: false

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: traefik
  clusterIssuer: letsencrypt-prod
  path: /
  pathType: Prefix
  annotations: {}

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}
